
project_id = "your_supabase_project_id"

[functions."stock-data"]
verify_jwt = false

[functions."currency-exchange"]
verify_jwt = false

[functions."create-checkout"]
verify_jwt = false

[functions."check-subscription"]
verify_jwt = false

[functions."customer-portal"]
verify_jwt = false

[functions."stripe-webhooks"]
verify_jwt = false
